version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./static:/static
    environment:
      - DJANGO_SECRET_KEY=troque-em-producao-use-uma-chave-longa-e-aleatoria
      - DEBUG=True
      # URL do agente nmap local (nmap_agent.py rodando no host Windows)
      - NMAP_AGENT_URL=http://host.docker.internal:9998/scan
    restart: unless-stopped
    cap_add:
      - NET_RAW
      - NET_ADMIN
