# Generated by Django 5.0.6 on 2026-04-10 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.EmailField(max_length=254, unique=True, verbose_name='Endereço de E-mail')),
                ('usuario', models.CharField(max_length=150, verbose_name='Usuário')),
                ('senha', models.CharField(blank=True, help_text='Senha da conta de e-mail', max_length=255, verbose_name='Senha')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('servidor_email', models.CharField(blank=True, max_length=100, verbose_name='Servidor de E-mail')),
                ('cota_mb', models.IntegerField(blank=True, null=True, verbose_name='Cota (MB)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'E-mail Institucional',
                'verbose_name_plural': 'E-mails Institucionais',
                'ordering': ['endereco'],
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_tipo', models.CharField(max_length=50, verbose_name='Tipo de Dispositivo')),
                ('dispositivo_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Dispositivo')),
                ('ip', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=10, verbose_name='Status')),
                ('latencia_ms', models.FloatField(blank=True, null=True, verbose_name='Latência (ms)')),
                ('mac_address', models.CharField(blank=True, default='', max_length=17, verbose_name='MAC Address')),
                ('fabricante_mac', models.CharField(blank=True, default='', max_length=255, verbose_name='Fabricante (MAC)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Histórico de Ping',
                'verbose_name_plural': 'Histórico de Pings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=100, verbose_name='Campus')),
                ('bloco', models.CharField(max_length=50, verbose_name='Bloco')),
                ('andar', models.CharField(blank=True, max_length=20, verbose_name='Andar')),
                ('sala', models.CharField(blank=True, max_length=50, verbose_name='Sala')),
                ('rack', models.CharField(blank=True, max_length=50, verbose_name='Rack')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'ordering': ['campus', 'bloco', 'sala'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('ip_servidor', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Servidor')),
                ('responsavel', models.CharField(blank=True, max_length=150, verbose_name='Responsável')),
                ('certificado_expiracao', models.DateField(blank=True, null=True, verbose_name='Validade do Certificado SSL')),
                ('usuario', models.CharField(blank=True, help_text='Usuário para acesso ao site (opcional)', max_length=150, verbose_name='Usuário')),
                ('senha', models.CharField(blank=True, help_text='Senha para acesso ao site (opcional)', max_length=255, verbose_name='Senha')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Subrede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(help_text='Ex: 192.168.1.0/24', max_length=18, unique=True, verbose_name='CIDR')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='Gateway')),
                ('vlan', models.CharField(blank=True, max_length=20, verbose_name='VLAN')),
                ('finalidade', models.CharField(blank=True, max_length=150, verbose_name='Finalidade')),
                ('faixa_inicio', models.GenericIPAddressField(blank=True, null=True, verbose_name='Início da Faixa')),
                ('faixa_fim', models.GenericIPAddressField(blank=True, null=True, verbose_name='Fim da Faixa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Subrede',
                'verbose_name_plural': 'Subredes',
                'ordering': ['cidr'],
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='Hostname')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('mac', models.CharField(blank=True, help_text='Ex: AA:BB:CC:DD:EE:FF', max_length=17, verbose_name='MAC Address')),
                ('sistema_operacional', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operacional')),
                ('usuario_responsavel', models.CharField(blank=True, max_length=150, verbose_name='Usuário Responsável')),
                ('senha', models.CharField(blank=True, help_text='Senha de acesso ao sistema/computador', max_length=255, verbose_name='Senha')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ip', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ssid', models.CharField(blank=True, max_length=100, verbose_name='SSID')),
                ('canal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Canal')),
                ('frequencia', models.CharField(choices=[('2.4GHz', '2.4 GHz'), ('5GHz', '5 GHz'), ('Dual', 'Dual Band')], default='Dual', max_length=10, verbose_name='Frequência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.fabricante', verbose_name='Fabricante')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Access Point',
                'verbose_name_plural': 'Access Points',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Roteador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ip', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Tags')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.fabricante', verbose_name='Fabricante')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Roteador',
                'verbose_name_plural': 'Roteadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ip', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('quantidade_portas', models.PositiveIntegerField(default=24, verbose_name='Qtd. de Portas')),
                ('vlans', models.CharField(blank=True, help_text='Ex: 1,10,20,100', max_length=255, verbose_name='VLANs')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('tags', models.CharField(blank=True, help_text='Separadas por vírgula', max_length=255, verbose_name='Tags')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.fabricante', verbose_name='Fabricante')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.localizacao', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Switch',
                'verbose_name_plural': 'Switches',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PortaSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da Porta')),
                ('velocidade', models.CharField(choices=[('10M', '10 Mbps'), ('100M', '100 Mbps'), ('1G', '1 Gbps'), ('10G', '10 Gbps')], default='1G', max_length=10, verbose_name='Velocidade')),
                ('vlan', models.CharField(blank=True, max_length=20, verbose_name='VLAN')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('ERRO', 'Erro')], default='INATIVA', max_length=10, verbose_name='Status')),
                ('dispositivo_conectado', models.CharField(blank=True, max_length=150, verbose_name='Dispositivo Conectado')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portas', to='inventory.switch', verbose_name='Switch')),
            ],
            options={
                'verbose_name': 'Porta de Switch',
                'verbose_name_plural': 'Portas de Switch',
                'ordering': ['switch', 'numero'],
                'unique_together': {('switch', 'numero')},
            },
        ),
    ]
